runtime: nodejs18
service: promptelt

handlers:
  # Serve static files
  - url: /assets
    static_dir: assets
    secure: always
    http_headers:
      Cache-Control: "public, max-age=31536000"

  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg))$
    static_files: \1
    upload: .*\.(js|css|png|jpg|jpeg|gif|ico|svg)$
    secure: always
    http_headers:
      Cache-Control: "public, max-age=31536000"

  # Serve index.html for all other routes (SPA routing)
  - url: /.*
    static_files: index.html
    upload: index.html
    secure: always
    http_headers:
      Cache-Control: "no-cache, no-store, must-revalidate"
      Pragma: "no-cache"
      Expires: "0"

env_variables:
  NODE_ENV: "production"

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 0
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10 